development:
  sessions:
    default:
      database: scraper_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: scraper_test
      hosts:
        - localhost:27017
